// Generate typescript types for this addon

const fs = require("fs");
const path = require("path");

require("esbuild-register");
const { ADDON_NAME } = require("../src/util/constants.ts");

const templatePath = path.join(__dirname, "../types/generated.d.ts.template");
const outputPath = path.join(__dirname, "../types/generated.d.ts");

const template = fs.readFileSync(templatePath, "utf8");
const output = template.replace(/__ADDON_NAME__/g, ADDON_NAME);

const HEADER = `/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY ⚠️
 *
 * This file was generated by src/generateTypes.js using
 * types/generated.d.ts.template to auto fill the addon name
 *
 * Modify the template for changes to stick
 */\n\n\n
`;
fs.writeFileSync(outputPath, HEADER + output);
console.log(`Generated global.d.ts with ADDON_NAME="${ADDON_NAME}"`);
